# Tomcat
server:
  # 端 口
  port: 8080
  # Servlet
  servlet:
    # Session
    session:
      # 超 时 时 间
      timeout: 120m

# Spring 配置
spring:
  session:
    timeout: 120m
  # Druid Pool 运行环境
  profiles:
    # 运 行 环 境
    active: dev
