# Tomcat
server:
  # 端 口
  port: 8080
  # Servlet
  servlet:
    # Session
    session:
      # 超 时 时 间
      timeout: 120m

# Spring 配置
spring:
  session:
    timeout: 120m
  # Druid Pool 运行环境
  profiles:
    # 运 行 环 境
    active: dev

# 系 统 配 置 信 息
project:
  # 权 限 配 置
  security:
    # 开 启 超 级 管 理 员 账 号 -- 不需要验证权限
    super-auth-open: true
    # 超 级 管 理 员 角 色 -- 不需要验证权限
    super-role: admin
    # 允 许 同 一 账 号 多 端 登 录 个 数
    maximum: 1
    # 记 住 密 码 KEY
    remember-key: VUHE_REMEMBER
    # 不 需 要 权 限 拦 截 的 接 口 配 置
    open-api:
      - /login/**  # 开放登录接口
      - /system/captcha/** # 开放验证码接口
      - /assets/** # 开放静态资源
      - /admin/** # 开放静态资源
      - /component/** # 开放静态资源
      - /favicon.ico # 开放FAVICON

# 日志配置
#logging:
#  level:
#    org:
#      ktorm: debug
#  config: classpath:logback-spring.xml

# Document 配 置 信 息
springdoc:
  swagger:
    # 文 档 标 题
    title: Admin API
    # 描 述 信 息
    describe: 管 理 系 统 模 版
    # 协 议
    licence: MIT
    # 协 议 地 址
    licence-url: https://github.com/vuhe/AdminTemplate/blob/main/LICENSE
    # 组 织 信 息
    terms-of-service-url: https://github.com/vuhe
    # 版 本 信 息
    version: Release 2.0.0
    # 扩 展 信 息
    contact:
      # 作 者
      name: vuhe
      # 连 接
      url: https://github.com/vuhe
      # 邮 箱
      email: zhuhe202@qq.com
  swagger-ui:
    # 是 否 开 启
    enabled: true
  # 扫 包 路 径
  packages-to-scan: top.vuhe
